apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-bonus-deployment
  labels:
    app: ms-bonus-deployment
spec:
  selector:
    matchLabels:
      app: ms-bonus-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-bonus-deployment
    spec:
      containers:
        - name: ms-bonus
          image: ivanguajardo13/ms-bonus-pep2
          ports:
            - containerPort: 8099
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_BONUS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_BONUS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_BONUS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_BONUS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_BONUS
