apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-vehicles-deployment
  labels:
    app: ms-vehicles-deployment
spec:
  selector:
    matchLabels:
      app: ms-vehicles-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-vehicles-deployment
    spec:
      containers:
        - name: ms-vehicles
          image: ivanguajardo13/ms-vehicles-pep2
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "8092"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_VEHICLES
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_VEHICLES
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_VEHICLES
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_VEHICLES
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_VEHICLES
---
apiVersion: v1
kind: Service
metadata:
  name: ms-vehicles-service
  labels:
    app: ms-vehicles-service
spec:
  selector:
    app: ms-vehicles-deployment
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: LoadBalancer