--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ticket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket (
    id_ticket bigint NOT NULL,
    base_price integer NOT NULL,
    brand_bonus double precision NOT NULL,
    discount_for_bonus double precision NOT NULL,
    discount_for_repairs double precision NOT NULL,
    discount_per_day double precision NOT NULL,
    entry_date timestamp(6) without time zone,
    exit_date timestamp(6) without time zone,
    exit_time time(6) without time zone,
    license_plate bigint,
    pickup_date timestamp(6) without time zone,
    pickup_time time(6) without time zone,
    surcharge_for_age double precision NOT NULL,
    surcharge_for_delay double precision NOT NULL,
    surcharge_forkm double precision NOT NULL,
    total_price integer NOT NULL,
    total_repair_amount bigint
);


ALTER TABLE public.ticket OWNER TO postgres;

--
-- Name: ticket_entity_type_of_repairs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_entity_type_of_repairs (
    ticket_entity_id_ticket bigint NOT NULL,
    type_of_repairs integer
);


ALTER TABLE public.ticket_entity_type_of_repairs OWNER TO postgres;

--
-- Name: ticket_id_ticket_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket ALTER COLUMN id_ticket ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_id_ticket_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: ticket; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ticket (id_ticket, base_price, brand_bonus, discount_for_bonus, discount_for_repairs, discount_per_day, entry_date, exit_date, exit_time, license_plate, pickup_date, pickup_time, surcharge_for_age, surcharge_for_delay, surcharge_forkm, total_price, total_repair_amount) FROM stdin;
1	1040000	5	10	20	2.5	2024-05-28 04:00:00	2024-05-30 11:00:00	15:00:00	1	2024-06-01 06:00:00	10:00:00	10	5	15	230	48
\.


--
-- Data for Name: ticket_entity_type_of_repairs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ticket_entity_type_of_repairs (ticket_entity_id_ticket, type_of_repairs) FROM stdin;
1	1
1	2
1	3
\.


--
-- Name: ticket_id_ticket_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ticket_id_ticket_seq', 1, true);


--
-- Name: ticket ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (id_ticket);


--
-- Name: ticket_entity_type_of_repairs fknitlsxlbb8ysi6t33wbdhjvy6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_entity_type_of_repairs
    ADD CONSTRAINT fknitlsxlbb8ysi6t33wbdhjvy6 FOREIGN KEY (ticket_entity_id_ticket) REFERENCES public.ticket(id_ticket);


--
-- PostgreSQL database dump complete
--

